import { GetServerSideProps, NextPage } from 'next';
import Head from 'next/head';

import { fetchJobList } from '../redux/slices/jobList';
import { wrapper } from '../redux';

const Home: NextPage = () => {
	return (
		<div>
			<Head>
				<title>Job Board App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<h1>
				Hello World!
			</h1>
		</div>
	);
};

export const getServerSideProps: GetServerSideProps = wrapper.getServerSideProps(
	(store) => async () => {
		await store.dispatch(fetchJobList());
		return {
			props: {},
		};
	}
);

export default Home;